### PR TITLE
Add edit modal slideover option

### PR DESCRIPTION
**Pull request by ryanmortier**

### CODE REVIEW

**Comment by mokhosh** [comment]
looks good, thanks.
do you mind adding it to the readme too?

**Comment by ryanmortier** [comment]
> looks good, thanks. do you mind adding it to the readme too?

Sure, I won't be able to get to this until Monday though. Thanks!

**Comment by ryanmortier** [comment]
Should be good to go, let me know if you need any other changes.

**Comment by mokhosh** [comment]
Thanks

**Pull request merged**
